import { T } from '../theme/tokens'
import { useApiData } from '../api/hooks'
import type { RagSuggestions } from '../types/api'
import { SectionLabel } from './primitives/SectionLabel'

/** Per-student or per-question RAG coaching panel. */
export function RagPanel({
  audience,
  subjectId,
  sectionNumber,
}: {
  audience: 'student' | 'question'
  subjectId: string
  sectionNumber: number
}) {
  const path = `/rag/${audience}/${encodeURIComponent(subjectId)}`
  const { data, error, loading } = useApiData<RagSuggestions>(path)
  const title = audience === 'student' ? 'Coaching Suggestions · RAG' : 'Suggested Teaching Feedback · RAG'

  return (
    <div style={{ padding: 24, background: T.accentSoft, border: `1px solid ${T.accent}` }}>
      <SectionLabel n={sectionNumber}>{title}</SectionLabel>

      {loading && (
        <div style={{ fontFamily: T.fMono, fontSize: 11, color: T.ink2, lineHeight: 1.6 }}>
          Generating… first call on a cold backend can take a couple of minutes while the sentence-transformers
          model downloads and embeds {'~'}34k records. Subsequent queries hit the cached Chroma collection.
        </div>
      )}

      {error && (
        <div style={{ fontFamily: T.fMono, fontSize: 11, color: T.danger }}>
          {error}
        </div>
      )}

      {data && data.bullets.length > 0 && (
        <ul style={{ margin: 0, paddingLeft: 20, fontFamily: T.fSans, fontSize: 13.5, color: T.ink, lineHeight: 1.7 }}>
          {data.bullets.map((b, i) => (
            <li key={i} style={{ marginBottom: 6 }}>{b}</li>
          ))}
        </ul>
      )}

      {data && data.bullets.length === 0 && !loading && !error && (
        <div style={{ fontFamily: T.fMono, fontSize: 11, color: T.ink3, lineHeight: 1.6 }}>
          No suggestions — this typically means the OpenAI key isn't set, ChromaDB isn't installed, or the subject
          doesn't have enough submissions for the RAG pipeline yet.
        </div>
      )}

      {data && (data.session_id || data.session_id === null) && (
        <div style={{ marginTop: 14, fontFamily: T.fMono, fontSize: 10.5, color: T.ink3 }}>
          Generated by rag.generate_{audience === 'student' ? 'assistant' : 'cluster'}_suggestions · session{' '}
          <code style={{ background: '#fff', padding: '1px 4px' }}>{data.session_id ?? 'default'}</code>
        </div>
      )}
    </div>
  )
}
