import { AnimatePresence, motion } from 'framer-motion'
import { T } from '../theme/tokens'
import { useApiData } from '../api/hooks'
import type { RagSuggestions } from '../types/api'
import { SectionLabel } from './primitives/SectionLabel'
import { Skeleton } from './primitives/Skeleton'

/** Per-student or per-question RAG coaching panel. */
export function RagPanel({
  audience,
  subjectId,
  sectionNumber,
}: {
  audience: 'student' | 'question'
  subjectId: string
  sectionNumber: number
}) {
  const path = `/rag/${audience}/${encodeURIComponent(subjectId)}`
  const { data, error, loading } = useApiData<RagSuggestions>(path)
  const title = audience === 'student' ? 'Coaching Suggestions · RAG' : 'Suggested Teaching Feedback · RAG'

  return (
    <div style={{ padding: 24, background: T.accentSoft, border: `1px solid ${T.accent}` }}>
      <SectionLabel n={sectionNumber}>{title}</SectionLabel>

      <AnimatePresence mode="wait" initial={false}>
        {loading && (
          <motion.div
            key="skeleton"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.18 }}
            aria-label="Loading suggestions"
          >
            <Skeleton variant="text" rows={3} />
          </motion.div>
        )}
        {!loading && error && (
          <motion.div
            key="error"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            style={{ fontFamily: T.fMono, fontSize: 11, color: T.danger }}
          >
            {error}
          </motion.div>
        )}
        {!loading && !error && data && data.bullets.length > 0 && (
          <motion.ul
            key="bullets"
            initial="initial"
            animate="animate"
            variants={{ initial: {}, animate: { transition: { staggerChildren: 0.06 } } }}
            style={{ margin: 0, paddingLeft: 20, fontFamily: T.fSans, fontSize: 13.5, color: T.ink, lineHeight: 1.7 }}
          >
            {data.bullets.map((b, i) => (
              <motion.li
                key={i}
                variants={{ initial: { opacity: 0, x: -6 }, animate: { opacity: 1, x: 0 } }}
                transition={{ duration: 0.3, ease: 'easeOut' }}
                style={{ marginBottom: 6 }}
              >
                {b}
              </motion.li>
            ))}
          </motion.ul>
        )}
      </AnimatePresence>

      {data && data.bullets.length === 0 && !loading && !error && (
        <div style={{ fontFamily: T.fMono, fontSize: 11, color: T.ink3, lineHeight: 1.6 }}>
          No suggestions — this typically means the OpenAI key isn't set, ChromaDB isn't installed, or the subject
          doesn't have enough submissions for the RAG pipeline yet.
        </div>
      )}

      {data && (data.session_id || data.session_id === null) && (
        <div style={{ marginTop: 14, fontFamily: T.fMono, fontSize: 10.5, color: T.ink3 }}>
          Generated by rag.generate_{audience === 'student' ? 'assistant' : 'cluster'}_suggestions · session{' '}
          <code style={{ background: '#fff', padding: '1px 4px' }}>{data.session_id ?? 'default'}</code>
        </div>
      )}
    </div>
  )
}
